#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SlidingLayerLib.Resource", IsApplication=false)]

namespace SlidingLayerLib
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int changeStateOnTap = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int offsetDistance = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int previewOffsetDistance = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int shadowDrawable = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int shadowSize = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int stickTo = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int bottom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int left = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int right = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int top = 2130903043;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingLayer = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public static int SlidingLayer_changeStateOnTap = 2;
			
			// aapt resource value: 3
			public static int SlidingLayer_offsetDistance = 3;
			
			// aapt resource value: 4
			public static int SlidingLayer_previewOffsetDistance = 4;
			
			// aapt resource value: 0
			public static int SlidingLayer_shadowDrawable = 0;
			
			// aapt resource value: 1
			public static int SlidingLayer_shadowSize = 1;
			
			// aapt resource value: 5
			public static int SlidingLayer_stickTo = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
